language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
  # install a newer version of CMake:
  - sudo apt-get remove -y cmake
  - curl -fsSL http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh > /tmp/install-cmake.sh
  - chmod +x /tmp/install-cmake.sh
  - sudo /tmp/install-cmake.sh --prefix=/usr/local --exclude-subdir
  - pip install .
  - pip install mercurial==2.6.2
  # install Ninja
  - sudo apt-get install ninja-build
before_script:
  - /bin/bash .travis_init.sh
# command to run tests
script: python setup.py test 
